### ISSUE TITLE
`nufmt` roadmap

### ISSUE THREAD

**Issue by AucaCoyan** [fdncred/nufmt#11]
With the PR #7 merged, I need some guidelines to do what in what order, so here are some thoughts about the possible features and the things to fix.
As we work in issues and features, we can edit the list. 
# ❗ TODO
- [ ] clean `/examples/` folder
- [ ] make `clippy` happy
- [ ] The formatter adds always a `\n` at the end of the file. Sometimes the last character already is `\n`, so this duplicates the empty line and the end of the file. It would be cool if add a function to check if the last line is a empty line and add one if it false
- [ ] It is still not possible to format a string, only files.
- [ ] make tests
- [ ] With the file formatted (`--minified`), we need to add the indentation
- [ ] ... and make configurable with `Config` struct
- [ ] limit the max characters to `Config`
- [ ] make the formatter keep comments of code
- [ ] and endings of `;`, if they are relevant to nushell logic (delete them if they are unnecessary, like python)
- [ ] examine the input path: Is it a file? format it. Is it a directory? format the `.nu` files and skip the other files
- [ ] Format reports are nice. Add them!
- [ ] public the cargo package
- [ ] Make it available as a GitHub Action

**Comment by AucaCoyan** [comment]
added  
- [ ] add some ignore comment (`# nufmt ignore`)
to the list

**Comment by fdncred** [comment]
I recommend topiary-nushell frequently because it's so good right now. However, I'm not sure I'd adopt it as the official one because it does not use the nushell parser. It uses tree-sitter which nushell does not use. So, there's a chance these two parsers could/do diverge. I'm sure there are already things that are implemented in either parser that the other doesn't really support right now.

What we need is more contributors to nufmt.

**Comment by blindFS** [comment]
> What we need is more contributors to nufmt.

Agreed, but `new-nu-parser` is of higher priority IMHO.

**Comment by trymeouteh** [comment]
I have 2 questions on `nufmt`

1. Will it indent using tabs or will there be an option to use tabs instead of spaces?
2. Will `nufmt` also format `.nuon` files?
